version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
    versioning-strategy: increase
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">= 11.a"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
