# only validate PR title because it will be used as the merge commit title
titleOnly: true

# only allow these scopes
scopes:
  - lib
  - cli
  - plus
  - examples
  - readme
  - docs
  - website
  - release
  
# only allow these types
types:
  - feat
  - fix
  - chore
  - refactor
  - revert
