version = 1

test_patterns = ["/test/**/*.ts"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser",
    "jest"
  ]
  dialect = "typescript"
