pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      comment:
        message: Your pull request will be updated and merged automatically (do not update manually).
      merge:
        strict: smart
        method: squash
        strict_method: merge
      delete_head_branch: {}
