pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "#approved-reviews-by>=1"
      - -label~=(blocked|do-not-merge|no-squash|two-approvers)
    actions:
      comment:
        message: Your pull request will be updated and merged automatically (do not update manually).
      merge:
        strict: smart
        method: squash
        strict_method: merge
        commit_message: title+body
      delete_head_branch: {}
      dismiss_reviews: {}    
  - name: Automatic merge PRs with auto-merge label upon successful build
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart
        strict_method: merge
      delete_head_branch: {}
    conditions:
      - label=auto-merge
      - status-success=build      
