/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * IngressSpec describes the Ingress the user wishes to exist.
 */
export interface IngressspecExtensionsV1Beta1 {
  /**
   * IngressBackend describes all endpoints for a given service and port.
   */
  backend?: {
    /**
     * Specifies the name of the referenced service.
     */
    serviceName: string;
    servicePort: (string | null) | (number | null);
    [k: string]: any;
  };
  /**
   * A list of host rules used to configure the Ingress. If unspecified, or no rule matches, all traffic is sent to the default backend.
   */
  rules?:
    | {
        /**
         * Host is the fully qualified domain name of a network host, as defined by RFC 3986. Note the following deviations from the "host" part of the URI as defined in the RFC: 1. IPs are not allowed. Currently an IngressRuleValue can only apply to the
         * 	  IP in the Spec of the parent Ingress.
         * 2. The `:` delimiter is not respected because ports are not allowed.
         * 	  Currently the port of an Ingress is implicitly :80 for http and
         * 	  :443 for https.
         * Both these may change in the future. Incoming requests are matched against the host before the IngressRuleValue. If the host is unspecified, the Ingress routes all traffic based on the specified IngressRuleValue.
         */
        host?: string | null;
        /**
         * HTTPIngressRuleValue is a list of http selectors pointing to backends. In the example: http://<host>/<path>?<searchpart> -> backend where where parts of the url correspond to RFC 3986, this resource will be used to match against everything after the last '/' and before the first '?' or '#'.
         */
        http?: {
          /**
           * A collection of paths that map requests to backends.
           */
          paths: {
            /**
             * IngressBackend describes all endpoints for a given service and port.
             */
            backend: {
              /**
               * Specifies the name of the referenced service.
               */
              serviceName: string;
              servicePort: (string | null) | (number | null);
              [k: string]: any;
            };
            /**
             * Path is an extended POSIX regex as defined by IEEE Std 1003.1, (i.e this follows the egrep/unix syntax, not the perl syntax) matched against the path of an incoming request. Currently it can contain characters disallowed from the conventional "path" part of a URL as defined by RFC 3986. Paths must begin with a '/'. If unspecified, the path defaults to a catch all sending traffic to the backend.
             */
            path?: string | null;
            [k: string]: any;
          }[];
          [k: string]: any;
        };
        [k: string]: any;
      }[]
    | null;
  /**
   * TLS configuration. Currently the Ingress only supports a single TLS port, 443. If multiple members of this list specify different hosts, they will be multiplexed on the same port according to the hostname specified through the SNI TLS extension, if the ingress controller fulfilling the ingress supports SNI.
   */
  tls?:
    | {
        /**
         * Hosts are a list of hosts included in the TLS certificate. The values in this list must match the name/s used in the tlsSecret. Defaults to the wildcard host setting for the loadbalancer controller fulfilling this Ingress, if left unspecified.
         */
        hosts?: (string | null)[] | null;
        /**
         * SecretName is the name of the secret used to terminate SSL traffic on 443. Field is left optional to allow SSL routing based on SNI hostname alone. If the SNI host in a listener conflicts with the "Host" header field used by an IngressRule, the SNI host is used for termination and value of the Host header is used for routing.
         */
        secretName?: string | null;
        [k: string]: any;
      }[]
    | null;
  [k: string]: any;
}
