// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * 
 *
 * @schema CronTab
 */
export class CronTab extends ApiObject {
  /**
   * Defines a "CronTab" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialiation props
   */
  public constructor(scope: Construct, id: string, props: CronTabOptions = {}) {
    super(scope, id, {
      ...props,
      kind: 'CronTab',
      apiVersion: 'stable.example.com/v1',
    });
  }
}

/**
 * @schema CronTab
 */
export interface CronTabOptions {
  /**
   * @schema CronTab#spec
   */
  readonly spec?: CronTabSpec;

}

/**
 * @schema CronTabSpec
 */
export interface CronTabSpec {
  /**
   * @schema CronTabSpec#cronSpec
   */
  readonly cronSpec?: string;

  /**
   * @schema CronTabSpec#image
   */
  readonly image?: string;

  /**
   * @schema CronTabSpec#replicas
   */
  readonly replicas?: number;

}

