// generated by cdk8s
import { ApiObject, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * A Configuration is the description of a Crossplane Configuration package.
 *
 * @schema Configuration
 */
export class Configuration extends ApiObject {
  /**
   * Returns the apiVersion and kind for "Configuration"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'meta.pkg.crossplane.io/v1alpha1',
    kind: 'Configuration',
  }

  /**
   * Renders a Kubernetes manifest for "Configuration".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ConfigurationProps): any {
    return {
      ...Configuration.GVK,
      ...props,
    };
  }

  /**
   * Defines a "Configuration" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ConfigurationProps) {
    super(scope, id, Configuration.manifest(props));
  }
}

/**
 * A Configuration is the description of a Crossplane Configuration package.
 *
 * @schema Configuration
 */
export interface ConfigurationProps {
  /**
   * @schema Configuration#metadata
   */
  readonly metadata?: any;

  /**
   * ConfigurationSpec specifies the configuration of a Configuration.
   *
   * @schema Configuration#spec
   */
  readonly spec: ConfigurationSpec;

}

/**
 * ConfigurationSpec specifies the configuration of a Configuration.
 *
 * @schema ConfigurationSpec
 */
export interface ConfigurationSpec {
  /**
   * Semantic version constraints of Crossplane that package is compatible with.
   *
   * @schema ConfigurationSpec#crossplane
   */
  readonly crossplane?: ConfigurationSpecCrossplane;

  /**
   * Dependencies on other packages.
   *
   * @schema ConfigurationSpec#dependsOn
   */
  readonly dependsOn?: ConfigurationSpecDependsOn[];

}

/**
 * Semantic version constraints of Crossplane that package is compatible with.
 *
 * @schema ConfigurationSpecCrossplane
 */
export interface ConfigurationSpecCrossplane {
  /**
   * Semantic version constraints of Crossplane that package is compatible with.
   *
   * @schema ConfigurationSpecCrossplane#version
   */
  readonly version: string;

}

/**
 * Dependency is a dependency on another package. One of Provider or Configuration may be supplied.
 *
 * @schema ConfigurationSpecDependsOn
 */
export interface ConfigurationSpecDependsOn {
  /**
   * Configuration is the name of a Configuration package image.
   *
   * @schema ConfigurationSpecDependsOn#configuration
   */
  readonly configuration?: string;

  /**
   * Provider is the name of a Provider package image.
   *
   * @schema ConfigurationSpecDependsOn#provider
   */
  readonly provider?: string;

  /**
   * Version is the semantic version constraints of the dependency image.
   *
   * @schema ConfigurationSpecDependsOn#version
   */
  readonly version: string;

}

/**
 * A Provider is the description of a Crossplane Provider package.
 *
 * @schema Provider
 */
export class Provider extends ApiObject {
  /**
   * Returns the apiVersion and kind for "Provider"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'meta.pkg.crossplane.io/v1alpha1',
    kind: 'Provider',
  }

  /**
   * Renders a Kubernetes manifest for "Provider".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: ProviderProps): any {
    return {
      ...Provider.GVK,
      ...props,
    };
  }

  /**
   * Defines a "Provider" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: ProviderProps) {
    super(scope, id, Provider.manifest(props));
  }
}

/**
 * A Provider is the description of a Crossplane Provider package.
 *
 * @schema Provider
 */
export interface ProviderProps {
  /**
   * @schema Provider#metadata
   */
  readonly metadata?: any;

  /**
   * ProviderSpec specifies the configuration of a Provider.
   *
   * @schema Provider#spec
   */
  readonly spec: ProviderSpec;

}

/**
 * ProviderSpec specifies the configuration of a Provider.
 *
 * @schema ProviderSpec
 */
export interface ProviderSpec {
  /**
   * Configuration for the packaged Provider's controller.
   *
   * @schema ProviderSpec#controller
   */
  readonly controller: ProviderSpecController;

  /**
   * Semantic version constraints of Crossplane that package is compatible with.
   *
   * @schema ProviderSpec#crossplane
   */
  readonly crossplane?: ProviderSpecCrossplane;

  /**
   * Dependencies on other packages.
   *
   * @schema ProviderSpec#dependsOn
   */
  readonly dependsOn?: ProviderSpecDependsOn[];

}

/**
 * Configuration for the packaged Provider's controller.
 *
 * @schema ProviderSpecController
 */
export interface ProviderSpecController {
  /**
   * Image is the packaged Provider controller image.
   *
   * @schema ProviderSpecController#image
   */
  readonly image: string;

}

/**
 * Semantic version constraints of Crossplane that package is compatible with.
 *
 * @schema ProviderSpecCrossplane
 */
export interface ProviderSpecCrossplane {
  /**
   * Semantic version constraints of Crossplane that package is compatible with.
   *
   * @schema ProviderSpecCrossplane#version
   */
  readonly version: string;

}

/**
 * Dependency is a dependency on another package. One of Provider or Configuration may be supplied.
 *
 * @schema ProviderSpecDependsOn
 */
export interface ProviderSpecDependsOn {
  /**
   * Configuration is the name of a Configuration package image.
   *
   * @schema ProviderSpecDependsOn#configuration
   */
  readonly configuration?: string;

  /**
   * Provider is the name of a Provider package image.
   *
   * @schema ProviderSpecDependsOn#provider
   */
  readonly provider?: string;

  /**
   * Version is the semantic version constraints of the dependency image.
   *
   * @schema ProviderSpecDependsOn#version
   */
  readonly version: string;

}

