// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * ClusterInstallation is the Schema for the clusterinstallations API
 *
 * @schema ClusterInstallation
 */
export class ClusterInstallation extends ApiObject {
  /**
   * Defines a "ClusterInstallation" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialiation props
   */
  public constructor(scope: Construct, id: string, props: ClusterInstallationOptions) {
    super(scope, id, {
      ...props,
      kind: 'ClusterInstallation',
      apiVersion: 'mattermost.com/v1alpha1',
    });
  }
}

/**
 * ClusterInstallation is the Schema for the clusterinstallations API
 *
 * @schema ClusterInstallation
 */
export interface ClusterInstallationOptions {
  /**
   * @schema ClusterInstallation#metadata
   */
  readonly metadata?: any;

  /**
   * Specification of the desired behavior of the Mattermost cluster. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status
   *
   * @schema ClusterInstallation#spec
   */
  readonly spec: ClusterInstallationSpec;

}

/**
 * Specification of the desired behavior of the Mattermost cluster. More info: https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#spec-and-status
 *
 * @schema ClusterInstallationSpec
 */
export interface ClusterInstallationSpec {
  /**
   * If specified, affinity will define the pod's scheduling constraints
   *
   * @schema ClusterInstallationSpec#affinity
   */
  readonly affinity?: ClusterInstallationSpecAffinity;

  /**
   * BlueGreen defines the configuration of BlueGreen deployment for a ClusterInstallation
   *
   * @schema ClusterInstallationSpec#blueGreen
   */
  readonly blueGreen?: ClusterInstallationSpecBlueGreen;

  /**
   * Canary defines the configuration of Canary deployment for a ClusterInstallation
   *
   * @schema ClusterInstallationSpec#canary
   */
  readonly canary?: ClusterInstallationSpecCanary;

  /**
   * Database defines the database configuration for a ClusterInstallation.
   *
   * @schema ClusterInstallationSpec#database
   */
  readonly database?: ClusterInstallationSpecDatabase;

  /**
   * ElasticSearch defines the ElasticSearch configuration for a ClusterInstallation.
   *
   * @schema ClusterInstallationSpec#elasticSearch
   */
  readonly elasticSearch?: ClusterInstallationSpecElasticSearch;

  /**
   * Image defines the ClusterInstallation Docker image.
   *
   * @schema ClusterInstallationSpec#image
   */
  readonly image?: string;

  /**
   * @schema ClusterInstallationSpec#ingressAnnotations
   */
  readonly ingressAnnotations?: { [key: string]: string };

  /**
   * IngressName defines the name to be used when creating the ingress rules
   *
   * @schema ClusterInstallationSpec#ingressName
   */
  readonly ingressName: string;

  /**
   * Defines the probe to check if the application is up and running.
   *
   * @schema ClusterInstallationSpec#livenessProbe
   */
  readonly livenessProbe?: ClusterInstallationSpecLivenessProbe;

  /**
   * Optional environment variables to set in the Mattermost application pods.
   *
   * @schema ClusterInstallationSpec#mattermostEnv
   */
  readonly mattermostEnv?: ClusterInstallationSpecMattermostEnv[];

  /**
   * Secret that contains the mattermost license
   *
   * @schema ClusterInstallationSpec#mattermostLicenseSecret
   */
  readonly mattermostLicenseSecret?: string;

  /**
   * Minio defines the configuration of Minio for a ClusterInstallation.
   *
   * @schema ClusterInstallationSpec#minio
   */
  readonly minio?: ClusterInstallationSpecMinio;

  /**
   * NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
   *
   * @schema ClusterInstallationSpec#nodeSelector
   */
  readonly nodeSelector?: { [key: string]: string };

  /**
   * Defines the probe to check if the application is ready to accept traffic.
   *
   * @schema ClusterInstallationSpec#readinessProbe
   */
  readonly readinessProbe?: ClusterInstallationSpecReadinessProbe;

  /**
   * Replicas defines the number of replicas to use for the Mattermost app servers. Setting this will override the number of replicas set by 'Size'.
   *
   * @schema ClusterInstallationSpec#replicas
   */
  readonly replicas?: number;

  /**
   * Defines the resource requests and limits for the Mattermost app server pods.
   *
   * @schema ClusterInstallationSpec#resources
   */
  readonly resources?: ClusterInstallationSpecResources;

  /**
   * @schema ClusterInstallationSpec#serviceAnnotations
   */
  readonly serviceAnnotations?: { [key: string]: string };

  /**
   * Size defines the size of the ClusterInstallation. This is typically specified in number of users. This will set replica and resource requests/limits appropriately for the provided number of users. Accepted values are: 100users, 1000users, 5000users, 10000users, 250000users. Defaults to 5000users. Setting 'Replicas', 'Resources', 'Minio.Replicas', 'Minio.Resource', 'Database.Replicas', or 'Database.Resources' will override the values set by Size.
   *
   * @default 5000users. Setting 'Replicas', 'Resources', 'Minio.Replicas', 'Minio.Resource', 'Database.Replicas', or 'Database.Resources' will override the values set by Size.
   * @schema ClusterInstallationSpec#size
   */
  readonly size?: string;

  /**
   * @schema ClusterInstallationSpec#useServiceLoadBalancer
   */
  readonly useServiceLoadBalancer?: boolean;

  /**
   * Version defines the ClusterInstallation Docker image version.
   *
   * @schema ClusterInstallationSpec#version
   */
  readonly version?: string;

}

/**
 * If specified, affinity will define the pod's scheduling constraints
 *
 * @schema ClusterInstallationSpecAffinity
 */
export interface ClusterInstallationSpecAffinity {
  /**
   * Describes node affinity scheduling rules for the pod.
   *
   * @schema ClusterInstallationSpecAffinity#nodeAffinity
   */
  readonly nodeAffinity?: ClusterInstallationSpecAffinityNodeAffinity;

  /**
   * Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s)).
   *
   * @schema ClusterInstallationSpecAffinity#podAffinity
   */
  readonly podAffinity?: ClusterInstallationSpecAffinityPodAffinity;

  /**
   * Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node, zone, etc. as some other pod(s)).
   *
   * @schema ClusterInstallationSpecAffinity#podAntiAffinity
   */
  readonly podAntiAffinity?: ClusterInstallationSpecAffinityPodAntiAffinity;

}

/**
 * BlueGreen defines the configuration of BlueGreen deployment for a ClusterInstallation
 *
 * @schema ClusterInstallationSpecBlueGreen
 */
export interface ClusterInstallationSpecBlueGreen {
  /**
   * Blue defines the blue deployment.
   *
   * @schema ClusterInstallationSpecBlueGreen#blue
   */
  readonly blue?: ClusterInstallationSpecBlueGreenBlue;

  /**
   * Enable defines if BlueGreen deployment will be applied.
   *
   * @schema ClusterInstallationSpecBlueGreen#enable
   */
  readonly enable?: boolean;

  /**
   * Green defines the green deployment.
   *
   * @schema ClusterInstallationSpecBlueGreen#green
   */
  readonly green?: ClusterInstallationSpecBlueGreenGreen;

  /**
   * ProductionDeployment defines if the current production is blue or green.
   *
   * @schema ClusterInstallationSpecBlueGreen#productionDeployment
   */
  readonly productionDeployment?: string;

}

/**
 * Canary defines the configuration of Canary deployment for a ClusterInstallation
 *
 * @schema ClusterInstallationSpecCanary
 */
export interface ClusterInstallationSpecCanary {
  /**
   * Deployment defines the canary deployment.
   *
   * @schema ClusterInstallationSpecCanary#deployment
   */
  readonly deployment?: ClusterInstallationSpecCanaryDeployment;

  /**
   * Enable defines if a canary build will be deployed.
   *
   * @schema ClusterInstallationSpecCanary#enable
   */
  readonly enable?: boolean;

}

/**
 * Database defines the database configuration for a ClusterInstallation.
 *
 * @schema ClusterInstallationSpecDatabase
 */
export interface ClusterInstallationSpecDatabase {
  /**
   * Defines the backup retention policy.
   *
   * @schema ClusterInstallationSpecDatabase#backupRemoteDeletePolicy
   */
  readonly backupRemoteDeletePolicy?: string;

  /**
   * Defines the secret to be used when performing a database restore.
   *
   * @schema ClusterInstallationSpecDatabase#backupRestoreSecretName
   */
  readonly backupRestoreSecretName?: string;

  /**
   * Defines the interval for backups in cron expression format.
   *
   * @schema ClusterInstallationSpecDatabase#backupSchedule
   */
  readonly backupSchedule?: string;

  /**
   * Defines the secret to be used for uploading/restoring backup.
   *
   * @schema ClusterInstallationSpecDatabase#backupSecretName
   */
  readonly backupSecretName?: string;

  /**
   * Defines the object storage url for uploading backups.
   *
   * @schema ClusterInstallationSpecDatabase#backupURL
   */
  readonly backupURL?: string;

  /**
   * Defines the AWS S3 bucket where the Database Backup is stored. The operator will download the file to restore the data.
   *
   * @schema ClusterInstallationSpecDatabase#initBucketURL
   */
  readonly initBucketURL?: string;

  /**
   * Defines the number of database replicas. For redundancy use at least 2 replicas. Setting this will override the number of replicas set by 'Size'.
   *
   * @schema ClusterInstallationSpecDatabase#replicas
   */
  readonly replicas?: number;

  /**
   * Defines the resource requests and limits for the database pods.
   *
   * @schema ClusterInstallationSpecDatabase#resources
   */
  readonly resources?: ClusterInstallationSpecDatabaseResources;

  /**
   * Optionally enter the name of an already-existing Secret for connecting to the database. This secret should be configured as follows: 
 User-Managed Database   - Key: DB_CONNECTION_STRING | Value: <FULL_DATABASE_CONNECTION_STRING> Operator-Managed Database   - Key: ROOT_PASSWORD | Value: <ROOT_DATABASE_PASSWORD>   - Key: USER | Value: <USER_NAME>   - Key: PASSWORD | Value: <USER_PASSWORD>   - Key: DATABASE Value: <DATABASE_NAME> 
 Notes:   If you define all secret values for both User-Managed and   Operator-Managed database types, the User-Managed connection string will   take precedence and the Operator-Managed values will be ignored. If the   secret is left blank, the default behavior is to use an Operator-Managed   database with strong randomly-generated database credentials.
   *
   * @schema ClusterInstallationSpecDatabase#secret
   */
  readonly secret?: string;

  /**
   * Defines the storage size for the database. ie 50Gi
   *
   * @schema ClusterInstallationSpecDatabase#storageSize
   */
  readonly storageSize?: string;

  /**
   * @schema ClusterInstallationSpecDatabase#type
   */
  readonly type?: string;

}

/**
 * ElasticSearch defines the ElasticSearch configuration for a ClusterInstallation.
 *
 * @schema ClusterInstallationSpecElasticSearch
 */
export interface ClusterInstallationSpecElasticSearch {
  /**
   * @schema ClusterInstallationSpecElasticSearch#host
   */
  readonly host?: string;

  /**
   * @schema ClusterInstallationSpecElasticSearch#password
   */
  readonly password?: string;

  /**
   * @schema ClusterInstallationSpecElasticSearch#username
   */
  readonly username?: string;

}

/**
 * Defines the probe to check if the application is up and running.
 *
 * @schema ClusterInstallationSpecLivenessProbe
 */
export interface ClusterInstallationSpecLivenessProbe {
  /**
   * One and only one of the following should be specified. Exec specifies the action to take.
   *
   * @schema ClusterInstallationSpecLivenessProbe#exec
   */
  readonly exec?: ClusterInstallationSpecLivenessProbeExec;

  /**
   * Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.
   *
   * @default 3. Minimum value is 1.
   * @schema ClusterInstallationSpecLivenessProbe#failureThreshold
   */
  readonly failureThreshold?: number;

  /**
   * HTTPGet specifies the http request to perform.
   *
   * @schema ClusterInstallationSpecLivenessProbe#httpGet
   */
  readonly httpGet?: ClusterInstallationSpecLivenessProbeHttpGet;

  /**
   * Number of seconds after the container has started before liveness probes are initiated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   *
   * @schema ClusterInstallationSpecLivenessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
   *
   * @default 10 seconds. Minimum value is 1.
   * @schema ClusterInstallationSpecLivenessProbe#periodSeconds
   */
  readonly periodSeconds?: number;

  /**
   * Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness and startup. Minimum value is 1.
   *
   * @default 1. Must be 1 for liveness and startup. Minimum value is 1.
   * @schema ClusterInstallationSpecLivenessProbe#successThreshold
   */
  readonly successThreshold?: number;

  /**
   * TCPSocket specifies an action involving a TCP port. TCP hooks not yet supported TODO: implement a realistic TCP lifecycle hook
   *
   * @schema ClusterInstallationSpecLivenessProbe#tcpSocket
   */
  readonly tcpSocket?: ClusterInstallationSpecLivenessProbeTcpSocket;

  /**
   * Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   *
   * @default 1 second. Minimum value is 1. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   * @schema ClusterInstallationSpecLivenessProbe#timeoutSeconds
   */
  readonly timeoutSeconds?: number;

}

/**
 * EnvVar represents an environment variable present in a Container.
 *
 * @schema ClusterInstallationSpecMattermostEnv
 */
export interface ClusterInstallationSpecMattermostEnv {
  /**
   * Name of the environment variable. Must be a C_IDENTIFIER.
   *
   * @schema ClusterInstallationSpecMattermostEnv#name
   */
  readonly name: string;

  /**
   * Variable references $(VAR_NAME) are expanded using the previous defined environment variables in the container and any service environment variables. If a variable cannot be resolved, the reference in the input string will be unchanged. The $(VAR_NAME) syntax can be escaped with a double $$, ie: $$(VAR_NAME). Escaped references will never be expanded, regardless of whether the variable exists or not. Defaults to "".
   *
   * @default .
   * @schema ClusterInstallationSpecMattermostEnv#value
   */
  readonly value?: string;

  /**
   * Source for the environment variable's value. Cannot be used if value is not empty.
   *
   * @schema ClusterInstallationSpecMattermostEnv#valueFrom
   */
  readonly valueFrom?: ClusterInstallationSpecMattermostEnvValueFrom;

}

/**
 * Minio defines the configuration of Minio for a ClusterInstallation.
 *
 * @schema ClusterInstallationSpecMinio
 */
export interface ClusterInstallationSpecMinio {
  /**
   * Set to the bucket name of your external MinIO or S3.
   *
   * @schema ClusterInstallationSpecMinio#externalBucket
   */
  readonly externalBucket?: string;

  /**
   * Set to use an external MinIO deployment or S3. Must also set 'Secret' and 'ExternalBucket'.
   *
   * @schema ClusterInstallationSpecMinio#externalURL
   */
  readonly externalURL?: string;

  /**
   * Defines the number of Minio replicas. Supply 1 to run Minio in standalone mode with no redundancy. Supply 4 or more to run Minio in distributed mode. Note that it is not possible to upgrade Minio from standalone to distributed mode. Setting this will override the number of replicas set by 'Size'. More info: https://docs.min.io/docs/distributed-minio-quickstart-guide.html
   *
   * @schema ClusterInstallationSpecMinio#replicas
   */
  readonly replicas?: number;

  /**
   * Defines the resource requests and limits for the Minio pods.
   *
   * @schema ClusterInstallationSpecMinio#resources
   */
  readonly resources?: ClusterInstallationSpecMinioResources;

  /**
   * Optionally enter the name of already existing secret. Secret should have two values: "accesskey" and "secretkey". Required when "ExternalURL" is set.
   *
   * @schema ClusterInstallationSpecMinio#secret
   */
  readonly secret?: string;

  /**
   * Defines the storage size for Minio. ie 50Gi
   *
   * @schema ClusterInstallationSpecMinio#storageSize
   */
  readonly storageSize?: string;

}

/**
 * Defines the probe to check if the application is ready to accept traffic.
 *
 * @schema ClusterInstallationSpecReadinessProbe
 */
export interface ClusterInstallationSpecReadinessProbe {
  /**
   * One and only one of the following should be specified. Exec specifies the action to take.
   *
   * @schema ClusterInstallationSpecReadinessProbe#exec
   */
  readonly exec?: ClusterInstallationSpecReadinessProbeExec;

  /**
   * Minimum consecutive failures for the probe to be considered failed after having succeeded. Defaults to 3. Minimum value is 1.
   *
   * @default 3. Minimum value is 1.
   * @schema ClusterInstallationSpecReadinessProbe#failureThreshold
   */
  readonly failureThreshold?: number;

  /**
   * HTTPGet specifies the http request to perform.
   *
   * @schema ClusterInstallationSpecReadinessProbe#httpGet
   */
  readonly httpGet?: ClusterInstallationSpecReadinessProbeHttpGet;

  /**
   * Number of seconds after the container has started before liveness probes are initiated. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   *
   * @schema ClusterInstallationSpecReadinessProbe#initialDelaySeconds
   */
  readonly initialDelaySeconds?: number;

  /**
   * How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
   *
   * @default 10 seconds. Minimum value is 1.
   * @schema ClusterInstallationSpecReadinessProbe#periodSeconds
   */
  readonly periodSeconds?: number;

  /**
   * Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness and startup. Minimum value is 1.
   *
   * @default 1. Must be 1 for liveness and startup. Minimum value is 1.
   * @schema ClusterInstallationSpecReadinessProbe#successThreshold
   */
  readonly successThreshold?: number;

  /**
   * TCPSocket specifies an action involving a TCP port. TCP hooks not yet supported TODO: implement a realistic TCP lifecycle hook
   *
   * @schema ClusterInstallationSpecReadinessProbe#tcpSocket
   */
  readonly tcpSocket?: ClusterInstallationSpecReadinessProbeTcpSocket;

  /**
   * Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   *
   * @default 1 second. Minimum value is 1. More info: https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle#container-probes
   * @schema ClusterInstallationSpecReadinessProbe#timeoutSeconds
   */
  readonly timeoutSeconds?: number;

}

/**
 * Defines the resource requests and limits for the Mattermost app server pods.
 *
 * @schema ClusterInstallationSpecResources
 */
export interface ClusterInstallationSpecResources {
  /**
   * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
   *
   * @schema ClusterInstallationSpecResources#limits
   */
  readonly limits?: { [key: string]: string };

  /**
   * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
   *
   * @schema ClusterInstallationSpecResources#requests
   */
  readonly requests?: { [key: string]: string };

}

/**
 * Describes node affinity scheduling rules for the pod.
 *
 * @schema ClusterInstallationSpecAffinityNodeAffinity
 */
export interface ClusterInstallationSpecAffinityNodeAffinity {
  /**
   * The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node matches the corresponding matchExpressions; the node(s) with the highest sum are the most preferred.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinity#preferredDuringSchedulingIgnoredDuringExecution
   */
  readonly preferredDuringSchedulingIgnoredDuringExecution?: ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution[];

  /**
   * If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to an update), the system may or may not try to eventually evict the pod from its node.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinity#requiredDuringSchedulingIgnoredDuringExecution
   */
  readonly requiredDuringSchedulingIgnoredDuringExecution?: ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution;

}

/**
 * Describes pod affinity scheduling rules (e.g. co-locate this pod in the same node, zone, etc. as some other pod(s)).
 *
 * @schema ClusterInstallationSpecAffinityPodAffinity
 */
export interface ClusterInstallationSpecAffinityPodAffinity {
  /**
   * The scheduler will prefer to schedule pods to nodes that satisfy the affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node has pods which matches the corresponding podAffinityTerm; the node(s) with the highest sum are the most preferred.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinity#preferredDuringSchedulingIgnoredDuringExecution
   */
  readonly preferredDuringSchedulingIgnoredDuringExecution?: ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution[];

  /**
   * If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to a pod label update), the system may or may not try to eventually evict the pod from its node. When there are multiple elements, the lists of nodes corresponding to each podAffinityTerm are intersected, i.e. all terms must be satisfied.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinity#requiredDuringSchedulingIgnoredDuringExecution
   */
  readonly requiredDuringSchedulingIgnoredDuringExecution?: ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecution[];

}

/**
 * Describes pod anti-affinity scheduling rules (e.g. avoid putting this pod in the same node, zone, etc. as some other pod(s)).
 *
 * @schema ClusterInstallationSpecAffinityPodAntiAffinity
 */
export interface ClusterInstallationSpecAffinityPodAntiAffinity {
  /**
   * The scheduler will prefer to schedule pods to nodes that satisfy the anti-affinity expressions specified by this field, but it may choose a node that violates one or more of the expressions. The node that is most preferred is the one with the greatest sum of weights, i.e. for each node that meets all of the scheduling requirements (resource request, requiredDuringScheduling anti-affinity expressions, etc.), compute a sum by iterating through the elements of this field and adding "weight" to the sum if the node has pods which matches the corresponding podAffinityTerm; the node(s) with the highest sum are the most preferred.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinity#preferredDuringSchedulingIgnoredDuringExecution
   */
  readonly preferredDuringSchedulingIgnoredDuringExecution?: ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecution[];

  /**
   * If the anti-affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the anti-affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to a pod label update), the system may or may not try to eventually evict the pod from its node. When there are multiple elements, the lists of nodes corresponding to each podAffinityTerm are intersected, i.e. all terms must be satisfied.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinity#requiredDuringSchedulingIgnoredDuringExecution
   */
  readonly requiredDuringSchedulingIgnoredDuringExecution?: ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecution[];

}

/**
 * Blue defines the blue deployment.
 *
 * @schema ClusterInstallationSpecBlueGreenBlue
 */
export interface ClusterInstallationSpecBlueGreenBlue {
  /**
   * Image defines the base Docker image that will be used for the deployment. Required when BlueGreen or Canary is enabled.
   *
   * @schema ClusterInstallationSpecBlueGreenBlue#image
   */
  readonly image?: string;

  /**
   * IngressName defines the ingress name that will be used by the deployment. This option is not used for Canary builds.
   *
   * @schema ClusterInstallationSpecBlueGreenBlue#ingressName
   */
  readonly ingressName?: string;

  /**
   * Name defines the name of the deployment
   *
   * @schema ClusterInstallationSpecBlueGreenBlue#name
   */
  readonly name?: string;

  /**
   * Version defines the Docker image version that will be used for the deployment. Required when BlueGreen or Canary is enabled.
   *
   * @schema ClusterInstallationSpecBlueGreenBlue#version
   */
  readonly version?: string;

}

/**
 * Green defines the green deployment.
 *
 * @schema ClusterInstallationSpecBlueGreenGreen
 */
export interface ClusterInstallationSpecBlueGreenGreen {
  /**
   * Image defines the base Docker image that will be used for the deployment. Required when BlueGreen or Canary is enabled.
   *
   * @schema ClusterInstallationSpecBlueGreenGreen#image
   */
  readonly image?: string;

  /**
   * IngressName defines the ingress name that will be used by the deployment. This option is not used for Canary builds.
   *
   * @schema ClusterInstallationSpecBlueGreenGreen#ingressName
   */
  readonly ingressName?: string;

  /**
   * Name defines the name of the deployment
   *
   * @schema ClusterInstallationSpecBlueGreenGreen#name
   */
  readonly name?: string;

  /**
   * Version defines the Docker image version that will be used for the deployment. Required when BlueGreen or Canary is enabled.
   *
   * @schema ClusterInstallationSpecBlueGreenGreen#version
   */
  readonly version?: string;

}

/**
 * Deployment defines the canary deployment.
 *
 * @schema ClusterInstallationSpecCanaryDeployment
 */
export interface ClusterInstallationSpecCanaryDeployment {
  /**
   * Image defines the base Docker image that will be used for the deployment. Required when BlueGreen or Canary is enabled.
   *
   * @schema ClusterInstallationSpecCanaryDeployment#image
   */
  readonly image?: string;

  /**
   * IngressName defines the ingress name that will be used by the deployment. This option is not used for Canary builds.
   *
   * @schema ClusterInstallationSpecCanaryDeployment#ingressName
   */
  readonly ingressName?: string;

  /**
   * Name defines the name of the deployment
   *
   * @schema ClusterInstallationSpecCanaryDeployment#name
   */
  readonly name?: string;

  /**
   * Version defines the Docker image version that will be used for the deployment. Required when BlueGreen or Canary is enabled.
   *
   * @schema ClusterInstallationSpecCanaryDeployment#version
   */
  readonly version?: string;

}

/**
 * Defines the resource requests and limits for the database pods.
 *
 * @schema ClusterInstallationSpecDatabaseResources
 */
export interface ClusterInstallationSpecDatabaseResources {
  /**
   * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
   *
   * @schema ClusterInstallationSpecDatabaseResources#limits
   */
  readonly limits?: { [key: string]: string };

  /**
   * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
   *
   * @schema ClusterInstallationSpecDatabaseResources#requests
   */
  readonly requests?: { [key: string]: string };

}

/**
 * One and only one of the following should be specified. Exec specifies the action to take.
 *
 * @schema ClusterInstallationSpecLivenessProbeExec
 */
export interface ClusterInstallationSpecLivenessProbeExec {
  /**
   * Command is the command line to execute inside the container, the working directory for the command  is root ('/') in the container's filesystem. The command is simply exec'd, it is not run inside a shell, so traditional shell instructions ('|', etc) won't work. To use a shell, you need to explicitly call out to that shell. Exit status of 0 is treated as live/healthy and non-zero is unhealthy.
   *
   * @schema ClusterInstallationSpecLivenessProbeExec#command
   */
  readonly command?: string[];

}

/**
 * HTTPGet specifies the http request to perform.
 *
 * @schema ClusterInstallationSpecLivenessProbeHttpGet
 */
export interface ClusterInstallationSpecLivenessProbeHttpGet {
  /**
   * Host name to connect to, defaults to the pod IP. You probably want to set "Host" in httpHeaders instead.
   *
   * @schema ClusterInstallationSpecLivenessProbeHttpGet#host
   */
  readonly host?: string;

  /**
   * Custom headers to set in the request. HTTP allows repeated headers.
   *
   * @schema ClusterInstallationSpecLivenessProbeHttpGet#httpHeaders
   */
  readonly httpHeaders?: ClusterInstallationSpecLivenessProbeHttpGetHttpHeaders[];

  /**
   * Path to access on the HTTP server.
   *
   * @schema ClusterInstallationSpecLivenessProbeHttpGet#path
   */
  readonly path?: string;

  /**
   * Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
   *
   * @schema ClusterInstallationSpecLivenessProbeHttpGet#port
   */
  readonly port: ClusterInstallationSpecLivenessProbeHttpGetPort;

  /**
   * Scheme to use for connecting to the host. Defaults to HTTP.
   *
   * @default HTTP.
   * @schema ClusterInstallationSpecLivenessProbeHttpGet#scheme
   */
  readonly scheme?: string;

}

/**
 * TCPSocket specifies an action involving a TCP port. TCP hooks not yet supported TODO: implement a realistic TCP lifecycle hook
 *
 * @schema ClusterInstallationSpecLivenessProbeTcpSocket
 */
export interface ClusterInstallationSpecLivenessProbeTcpSocket {
  /**
   * Optional: Host name to connect to, defaults to the pod IP.
   *
   * @schema ClusterInstallationSpecLivenessProbeTcpSocket#host
   */
  readonly host?: string;

  /**
   * Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
   *
   * @schema ClusterInstallationSpecLivenessProbeTcpSocket#port
   */
  readonly port: ClusterInstallationSpecLivenessProbeTcpSocketPort;

}

/**
 * Source for the environment variable's value. Cannot be used if value is not empty.
 *
 * @schema ClusterInstallationSpecMattermostEnvValueFrom
 */
export interface ClusterInstallationSpecMattermostEnvValueFrom {
  /**
   * Selects a key of a ConfigMap.
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFrom#configMapKeyRef
   */
  readonly configMapKeyRef?: ClusterInstallationSpecMattermostEnvValueFromConfigMapKeyRef;

  /**
   * Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFrom#fieldRef
   */
  readonly fieldRef?: ClusterInstallationSpecMattermostEnvValueFromFieldRef;

  /**
   * Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFrom#resourceFieldRef
   */
  readonly resourceFieldRef?: ClusterInstallationSpecMattermostEnvValueFromResourceFieldRef;

  /**
   * Selects a key of a secret in the pod's namespace
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFrom#secretKeyRef
   */
  readonly secretKeyRef?: ClusterInstallationSpecMattermostEnvValueFromSecretKeyRef;

}

/**
 * Defines the resource requests and limits for the Minio pods.
 *
 * @schema ClusterInstallationSpecMinioResources
 */
export interface ClusterInstallationSpecMinioResources {
  /**
   * Limits describes the maximum amount of compute resources allowed. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
   *
   * @schema ClusterInstallationSpecMinioResources#limits
   */
  readonly limits?: { [key: string]: string };

  /**
   * Requests describes the minimum amount of compute resources required. If Requests is omitted for a container, it defaults to Limits if that is explicitly specified, otherwise to an implementation-defined value. More info: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
   *
   * @schema ClusterInstallationSpecMinioResources#requests
   */
  readonly requests?: { [key: string]: string };

}

/**
 * One and only one of the following should be specified. Exec specifies the action to take.
 *
 * @schema ClusterInstallationSpecReadinessProbeExec
 */
export interface ClusterInstallationSpecReadinessProbeExec {
  /**
   * Command is the command line to execute inside the container, the working directory for the command  is root ('/') in the container's filesystem. The command is simply exec'd, it is not run inside a shell, so traditional shell instructions ('|', etc) won't work. To use a shell, you need to explicitly call out to that shell. Exit status of 0 is treated as live/healthy and non-zero is unhealthy.
   *
   * @schema ClusterInstallationSpecReadinessProbeExec#command
   */
  readonly command?: string[];

}

/**
 * HTTPGet specifies the http request to perform.
 *
 * @schema ClusterInstallationSpecReadinessProbeHttpGet
 */
export interface ClusterInstallationSpecReadinessProbeHttpGet {
  /**
   * Host name to connect to, defaults to the pod IP. You probably want to set "Host" in httpHeaders instead.
   *
   * @schema ClusterInstallationSpecReadinessProbeHttpGet#host
   */
  readonly host?: string;

  /**
   * Custom headers to set in the request. HTTP allows repeated headers.
   *
   * @schema ClusterInstallationSpecReadinessProbeHttpGet#httpHeaders
   */
  readonly httpHeaders?: ClusterInstallationSpecReadinessProbeHttpGetHttpHeaders[];

  /**
   * Path to access on the HTTP server.
   *
   * @schema ClusterInstallationSpecReadinessProbeHttpGet#path
   */
  readonly path?: string;

  /**
   * Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
   *
   * @schema ClusterInstallationSpecReadinessProbeHttpGet#port
   */
  readonly port: ClusterInstallationSpecReadinessProbeHttpGetPort;

  /**
   * Scheme to use for connecting to the host. Defaults to HTTP.
   *
   * @default HTTP.
   * @schema ClusterInstallationSpecReadinessProbeHttpGet#scheme
   */
  readonly scheme?: string;

}

/**
 * TCPSocket specifies an action involving a TCP port. TCP hooks not yet supported TODO: implement a realistic TCP lifecycle hook
 *
 * @schema ClusterInstallationSpecReadinessProbeTcpSocket
 */
export interface ClusterInstallationSpecReadinessProbeTcpSocket {
  /**
   * Optional: Host name to connect to, defaults to the pod IP.
   *
   * @schema ClusterInstallationSpecReadinessProbeTcpSocket#host
   */
  readonly host?: string;

  /**
   * Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
   *
   * @schema ClusterInstallationSpecReadinessProbeTcpSocket#port
   */
  readonly port: ClusterInstallationSpecReadinessProbeTcpSocketPort;

}

/**
 * An empty preferred scheduling term matches all objects with implicit weight 0 (i.e. it's a no-op). A null preferred scheduling term matches no objects (i.e. is also a no-op).
 *
 * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution
 */
export interface ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution {
  /**
   * A node selector term, associated with the corresponding weight.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution#preference
   */
  readonly preference: ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference;

  /**
   * Weight associated with matching the corresponding nodeSelectorTerm, in the range 1-100.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecution#weight
   */
  readonly weight: number;

}

/**
 * If the affinity requirements specified by this field are not met at scheduling time, the pod will not be scheduled onto the node. If the affinity requirements specified by this field cease to be met at some point during pod execution (e.g. due to an update), the system may or may not try to eventually evict the pod from its node.
 *
 * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution
 */
export interface ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution {
  /**
   * Required. A list of node selector terms. The terms are ORed.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecution#nodeSelectorTerms
   */
  readonly nodeSelectorTerms: ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms[];

}

/**
 * The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
 *
 * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution
 */
export interface ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution {
  /**
   * Required. A pod affinity term, associated with the corresponding weight.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution#podAffinityTerm
   */
  readonly podAffinityTerm: ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm;

  /**
   * weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecution#weight
   */
  readonly weight: number;

}

/**
 * Defines a set of pods (namely those matching the labelSelector relative to the given namespace(s)) that this pod should be co-located (affinity) or not co-located (anti-affinity) with, where co-located is defined as running on a node whose value of the label with key <topologyKey> matches that of any node on which a pod of the set of pods is running
 *
 * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecution
 */
export interface ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecution {
  /**
   * A label query over a set of resources, in this case pods.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecution#labelSelector
   */
  readonly labelSelector?: ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector;

  /**
   * namespaces specifies which namespaces the labelSelector applies to (matches against); null or empty list means "this pod's namespace"
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecution#namespaces
   */
  readonly namespaces?: string[];

  /**
   * This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecution#topologyKey
   */
  readonly topologyKey: string;

}

/**
 * The weights of all of the matched WeightedPodAffinityTerm fields are added per-node to find the most preferred node(s)
 *
 * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecution
 */
export interface ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecution {
  /**
   * Required. A pod affinity term, associated with the corresponding weight.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecution#podAffinityTerm
   */
  readonly podAffinityTerm: ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm;

  /**
   * weight associated with matching the corresponding podAffinityTerm, in the range 1-100.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecution#weight
   */
  readonly weight: number;

}

/**
 * Defines a set of pods (namely those matching the labelSelector relative to the given namespace(s)) that this pod should be co-located (affinity) or not co-located (anti-affinity) with, where co-located is defined as running on a node whose value of the label with key <topologyKey> matches that of any node on which a pod of the set of pods is running
 *
 * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecution
 */
export interface ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecution {
  /**
   * A label query over a set of resources, in this case pods.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecution#labelSelector
   */
  readonly labelSelector?: ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector;

  /**
   * namespaces specifies which namespaces the labelSelector applies to (matches against); null or empty list means "this pod's namespace"
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecution#namespaces
   */
  readonly namespaces?: string[];

  /**
   * This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecution#topologyKey
   */
  readonly topologyKey: string;

}

/**
 * HTTPHeader describes a custom header to be used in HTTP probes
 *
 * @schema ClusterInstallationSpecLivenessProbeHttpGetHttpHeaders
 */
export interface ClusterInstallationSpecLivenessProbeHttpGetHttpHeaders {
  /**
   * The header field name
   *
   * @schema ClusterInstallationSpecLivenessProbeHttpGetHttpHeaders#name
   */
  readonly name: string;

  /**
   * The header field value
   *
   * @schema ClusterInstallationSpecLivenessProbeHttpGetHttpHeaders#value
   */
  readonly value: string;

}

/**
 * Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
 *
 * @schema ClusterInstallationSpecLivenessProbeHttpGetPort
 */
export class ClusterInstallationSpecLivenessProbeHttpGetPort {
  public static fromNumber(value: number): ClusterInstallationSpecLivenessProbeHttpGetPort {
    return new ClusterInstallationSpecLivenessProbeHttpGetPort(value);
  }
  public static fromString(value: string): ClusterInstallationSpecLivenessProbeHttpGetPort {
    return new ClusterInstallationSpecLivenessProbeHttpGetPort(value);
  }
  private constructor(value: any) {
    Object.defineProperty(this, 'resolve', { value: () => value });
  }
}

/**
 * Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
 *
 * @schema ClusterInstallationSpecLivenessProbeTcpSocketPort
 */
export class ClusterInstallationSpecLivenessProbeTcpSocketPort {
  public static fromNumber(value: number): ClusterInstallationSpecLivenessProbeTcpSocketPort {
    return new ClusterInstallationSpecLivenessProbeTcpSocketPort(value);
  }
  public static fromString(value: string): ClusterInstallationSpecLivenessProbeTcpSocketPort {
    return new ClusterInstallationSpecLivenessProbeTcpSocketPort(value);
  }
  private constructor(value: any) {
    Object.defineProperty(this, 'resolve', { value: () => value });
  }
}

/**
 * Selects a key of a ConfigMap.
 *
 * @schema ClusterInstallationSpecMattermostEnvValueFromConfigMapKeyRef
 */
export interface ClusterInstallationSpecMattermostEnvValueFromConfigMapKeyRef {
  /**
   * The key to select.
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromConfigMapKeyRef#key
   */
  readonly key: string;

  /**
   * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromConfigMapKeyRef#name
   */
  readonly name?: string;

  /**
   * Specify whether the ConfigMap or its key must be defined
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromConfigMapKeyRef#optional
   */
  readonly optional?: boolean;

}

/**
 * Selects a field of the pod: supports metadata.name, metadata.namespace, metadata.labels, metadata.annotations, spec.nodeName, spec.serviceAccountName, status.hostIP, status.podIP, status.podIPs.
 *
 * @schema ClusterInstallationSpecMattermostEnvValueFromFieldRef
 */
export interface ClusterInstallationSpecMattermostEnvValueFromFieldRef {
  /**
   * Version of the schema the FieldPath is written in terms of, defaults to "v1".
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromFieldRef#apiVersion
   */
  readonly apiVersion?: string;

  /**
   * Path of the field to select in the specified API version.
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromFieldRef#fieldPath
   */
  readonly fieldPath: string;

}

/**
 * Selects a resource of the container: only resources limits and requests (limits.cpu, limits.memory, limits.ephemeral-storage, requests.cpu, requests.memory and requests.ephemeral-storage) are currently supported.
 *
 * @schema ClusterInstallationSpecMattermostEnvValueFromResourceFieldRef
 */
export interface ClusterInstallationSpecMattermostEnvValueFromResourceFieldRef {
  /**
   * Container name: required for volumes, optional for env vars
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromResourceFieldRef#containerName
   */
  readonly containerName?: string;

  /**
   * Specifies the output format of the exposed resources, defaults to "1"
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromResourceFieldRef#divisor
   */
  readonly divisor?: string;

  /**
   * Required: resource to select
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromResourceFieldRef#resource
   */
  readonly resource: string;

}

/**
 * Selects a key of a secret in the pod's namespace
 *
 * @schema ClusterInstallationSpecMattermostEnvValueFromSecretKeyRef
 */
export interface ClusterInstallationSpecMattermostEnvValueFromSecretKeyRef {
  /**
   * The key of the secret to select from.  Must be a valid secret key.
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromSecretKeyRef#key
   */
  readonly key: string;

  /**
   * Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names TODO: Add other useful fields. apiVersion, kind, uid?
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromSecretKeyRef#name
   */
  readonly name?: string;

  /**
   * Specify whether the Secret or its key must be defined
   *
   * @schema ClusterInstallationSpecMattermostEnvValueFromSecretKeyRef#optional
   */
  readonly optional?: boolean;

}

/**
 * HTTPHeader describes a custom header to be used in HTTP probes
 *
 * @schema ClusterInstallationSpecReadinessProbeHttpGetHttpHeaders
 */
export interface ClusterInstallationSpecReadinessProbeHttpGetHttpHeaders {
  /**
   * The header field name
   *
   * @schema ClusterInstallationSpecReadinessProbeHttpGetHttpHeaders#name
   */
  readonly name: string;

  /**
   * The header field value
   *
   * @schema ClusterInstallationSpecReadinessProbeHttpGetHttpHeaders#value
   */
  readonly value: string;

}

/**
 * Name or number of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
 *
 * @schema ClusterInstallationSpecReadinessProbeHttpGetPort
 */
export class ClusterInstallationSpecReadinessProbeHttpGetPort {
  public static fromNumber(value: number): ClusterInstallationSpecReadinessProbeHttpGetPort {
    return new ClusterInstallationSpecReadinessProbeHttpGetPort(value);
  }
  public static fromString(value: string): ClusterInstallationSpecReadinessProbeHttpGetPort {
    return new ClusterInstallationSpecReadinessProbeHttpGetPort(value);
  }
  private constructor(value: any) {
    Object.defineProperty(this, 'resolve', { value: () => value });
  }
}

/**
 * Number or name of the port to access on the container. Number must be in the range 1 to 65535. Name must be an IANA_SVC_NAME.
 *
 * @schema ClusterInstallationSpecReadinessProbeTcpSocketPort
 */
export class ClusterInstallationSpecReadinessProbeTcpSocketPort {
  public static fromNumber(value: number): ClusterInstallationSpecReadinessProbeTcpSocketPort {
    return new ClusterInstallationSpecReadinessProbeTcpSocketPort(value);
  }
  public static fromString(value: string): ClusterInstallationSpecReadinessProbeTcpSocketPort {
    return new ClusterInstallationSpecReadinessProbeTcpSocketPort(value);
  }
  private constructor(value: any) {
    Object.defineProperty(this, 'resolve', { value: () => value });
  }
}

/**
 * A node selector term, associated with the corresponding weight.
 *
 * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference
 */
export interface ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference {
  /**
   * A list of node selector requirements by node's labels.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference#matchExpressions
   */
  readonly matchExpressions?: ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions[];

  /**
   * A list of node selector requirements by node's fields.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreference#matchFields
   */
  readonly matchFields?: ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields[];

}

/**
 * A null or empty node selector term matches no objects. The requirements of them are ANDed. The TopologySelectorTerm type implements a subset of the NodeSelectorTerm.
 *
 * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms
 */
export interface ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms {
  /**
   * A list of node selector requirements by node's labels.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms#matchExpressions
   */
  readonly matchExpressions?: ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions[];

  /**
   * A list of node selector requirements by node's fields.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTerms#matchFields
   */
  readonly matchFields?: ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields[];

}

/**
 * Required. A pod affinity term, associated with the corresponding weight.
 *
 * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm
 */
export interface ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm {
  /**
   * A label query over a set of resources, in this case pods.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm#labelSelector
   */
  readonly labelSelector?: ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector;

  /**
   * namespaces specifies which namespaces the labelSelector applies to (matches against); null or empty list means "this pod's namespace"
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm#namespaces
   */
  readonly namespaces?: string[];

  /**
   * This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm#topologyKey
   */
  readonly topologyKey: string;

}

/**
 * A label query over a set of resources, in this case pods.
 *
 * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector
 */
export interface ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector {
  /**
   * matchExpressions is a list of label selector requirements. The requirements are ANDed.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector#matchExpressions
   */
  readonly matchExpressions?: ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions[];

  /**
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * Required. A pod affinity term, associated with the corresponding weight.
 *
 * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm
 */
export interface ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm {
  /**
   * A label query over a set of resources, in this case pods.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm#labelSelector
   */
  readonly labelSelector?: ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector;

  /**
   * namespaces specifies which namespaces the labelSelector applies to (matches against); null or empty list means "this pod's namespace"
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm#namespaces
   */
  readonly namespaces?: string[];

  /**
   * This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching the labelSelector in the specified namespaces, where co-located is defined as running on a node whose value of the label with key topologyKey matches that of any node on which any of the selected pods is running. Empty topologyKey is not allowed.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTerm#topologyKey
   */
  readonly topologyKey: string;

}

/**
 * A label query over a set of resources, in this case pods.
 *
 * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector
 */
export interface ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector {
  /**
   * matchExpressions is a list of label selector requirements. The requirements are ANDed.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector#matchExpressions
   */
  readonly matchExpressions?: ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions[];

  /**
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * A node selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
 *
 * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions
 */
export interface ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions {
  /**
   * The label key that the selector applies to.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions#key
   */
  readonly key: string;

  /**
   * Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions#operator
   */
  readonly operator: string;

  /**
   * An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchExpressions#values
   */
  readonly values?: string[];

}

/**
 * A node selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
 *
 * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields
 */
export interface ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields {
  /**
   * The label key that the selector applies to.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields#key
   */
  readonly key: string;

  /**
   * Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields#operator
   */
  readonly operator: string;

  /**
   * An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityPreferredDuringSchedulingIgnoredDuringExecutionPreferenceMatchFields#values
   */
  readonly values?: string[];

}

/**
 * A node selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
 *
 * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions
 */
export interface ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions {
  /**
   * The label key that the selector applies to.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions#key
   */
  readonly key: string;

  /**
   * Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions#operator
   */
  readonly operator: string;

  /**
   * An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchExpressions#values
   */
  readonly values?: string[];

}

/**
 * A node selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
 *
 * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields
 */
export interface ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields {
  /**
   * The label key that the selector applies to.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields#key
   */
  readonly key: string;

  /**
   * Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields#operator
   */
  readonly operator: string;

  /**
   * An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch.
   *
   * @schema ClusterInstallationSpecAffinityNodeAffinityRequiredDuringSchedulingIgnoredDuringExecutionNodeSelectorTermsMatchFields#values
   */
  readonly values?: string[];

}

/**
 * A label query over a set of resources, in this case pods.
 *
 * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector
 */
export interface ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector {
  /**
   * matchExpressions is a list of label selector requirements. The requirements are ANDed.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector#matchExpressions
   */
  readonly matchExpressions?: ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions[];

  /**
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
 *
 * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions
 */
export interface ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions {
  /**
   * key is the label key that the selector applies to.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions#key
   */
  readonly key: string;

  /**
   * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions#operator
   */
  readonly operator: string;

  /**
   * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions#values
   */
  readonly values?: string[];

}

/**
 * A label query over a set of resources, in this case pods.
 *
 * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector
 */
export interface ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector {
  /**
   * matchExpressions is a list of label selector requirements. The requirements are ANDed.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector#matchExpressions
   */
  readonly matchExpressions?: ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions[];

  /**
   * matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is "key", the operator is "In", and the values array contains only "value". The requirements are ANDed.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelector#matchLabels
   */
  readonly matchLabels?: { [key: string]: string };

}

/**
 * A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
 *
 * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions
 */
export interface ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions {
  /**
   * key is the label key that the selector applies to.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions#key
   */
  readonly key: string;

  /**
   * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions#operator
   */
  readonly operator: string;

  /**
   * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityRequiredDuringSchedulingIgnoredDuringExecutionLabelSelectorMatchExpressions#values
   */
  readonly values?: string[];

}

/**
 * A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
 *
 * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions
 */
export interface ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions {
  /**
   * key is the label key that the selector applies to.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions#key
   */
  readonly key: string;

  /**
   * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions#operator
   */
  readonly operator: string;

  /**
   * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
   *
   * @schema ClusterInstallationSpecAffinityPodAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions#values
   */
  readonly values?: string[];

}

/**
 * A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.
 *
 * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions
 */
export interface ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions {
  /**
   * key is the label key that the selector applies to.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions#key
   */
  readonly key: string;

  /**
   * operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions#operator
   */
  readonly operator: string;

  /**
   * values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.
   *
   * @schema ClusterInstallationSpecAffinityPodAntiAffinityPreferredDuringSchedulingIgnoredDuringExecutionPodAffinityTermLabelSelectorMatchExpressions#values
   */
  readonly values?: string[];

}

