import { Lazy } from '../src';
import { resolve } from '../src/lazy';

test('lazy', () => {
  // GIVEN
  const hello = {
    number: Lazy.any({ produce: () => 1234 }),
    string: Lazy.any({ produce: () => 'hello' }),
    implicit: createImplictToken(908),
  };

  expect(resolve(hello)).toStrictEqual({
    number: 1234,
    string: 'hello',
    implicit: 908,
  });
});

// this is how union tokens are generated by cdk8s-cli
function createImplictToken(value: any) {
  const implicit = {};
  Object.defineProperty(implicit, 'resolve', { value: () => value });
  return implicit;
}