import { Lazy } from 'constructs-tokens-staging';
import { resolve } from '../src/_tokens';

test('lazy', () => {
  // GIVEN
  const hello = {
    number: Lazy.numberValue({ produce: () => 1234 }),
    string: Lazy.stringValue({ produce: () => 'hello' }),
    implicit: createImplictToken(908),
  };

  // THEN
  expect(hello).toStrictEqual({
    number: -1.8881545897087498e+289,
    string: '${Token[TOKEN.1]}',
    implicit: { },
  });

  expect(resolve(hello)).toStrictEqual({
    number: 1234,
    string: 'hello',
    implicit: 908,
  });
});

// this is how union tokens are generated by cdk8s-cli
function createImplictToken(value: any) {
  const implicit = {};
  Object.defineProperty(implicit, 'resolve', { value: () => value });
  return implicit;
}