// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * 
 *
 * @schema Foo
 */
export class Foo extends ApiObject {
  /**
   * Defines a "Foo" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: any = {}) {
    super(scope, name, {
      ...options,
      kind: 'Foo',
      apiVersion: 'samplecontroller.k8s.io/v1alpha1',
    });
  }
}

