// generated by cdk8s
import { ApiObject } from 'cdk8s';
import { Construct } from 'constructs';

/**
 * 
 *
 * @schema Metric
 */
export class Metric extends ApiObject {
  /**
   * Defines a "Metric" API object
   * @param scope the scope in which to define this object
   * @param name a scope-local name for the object
   * @param options configuration options
   */
  public constructor(scope: Construct, name: string, options: any = {}) {
    super(scope, name, {
      ...options,
      kind: 'Metric',
      apiVersion: 'autoscaling.internal.knative.dev/v1alpha1',
    });
  }
}

