"A macro for the autogenerated Jest rule"

load("@npm//jest-cli:index.bzl", _jest = "jest", _jest_test = "jest_test")

def jest_test(name, srcs = [], deps = [], jest_config = ":jest.config.js", **kwargs):
    args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
        "--verbose",
    ]
    args.extend(["--config", "$(rootpath %s)" % jest_config])

    _jest(
        name = name + ".update",
        data = [jest_config] + srcs + deps,
        args = ["--config", "$(rootpath %s)" % jest_config, "--updateSnapshot", "--verbose"],
        **kwargs
    )

    _jest_test(
        name = name,
        data = [jest_config] + srcs + deps,
        args = args,
        **kwargs
    )
