"A macro for the autogenerated Jest rule"

load("@npm//jest-cli:index.bzl", _jest = "jest", _jest_test = "jest_test")

def jest_test(name, srcs = [], deps = [], jest_config = "//:jest.config.js", snapshot_resolver = "//:snapshotResolver.js", **kwargs):
    args = [
        "--no-cache",
        "--no-watchman",
        "--ci",
        "--verbose",
    ]
    args.extend(["--config", "$(rootpath %s)" % jest_config])

    update_args = args + ["--updateSnapshot"]

    _jest(
        name = name + ".update",
        data = [jest_config, snapshot_resolver] + srcs + deps,
        args = update_args,
        templated_args = ["--nobazel_patch_module_resolver"],
        testonly = True,
        **kwargs
    )

    _jest_test(
        name = name,
        data = [jest_config, snapshot_resolver] + srcs + deps,
        args = args,
        **kwargs
    )
