// Generated by cdk8s
import { Volume } from './volume';

export interface ContainerMountOptions {
  /**
   * Determines how the volume should be propagated to containers running
   * on the host.
   *
   * Setting this property is relevant only for
   * `HostPathVolume`s.
   *
   * @see https://kubernetes.io/docs/concepts/storage/volumes/#hostpath-volume-types
   * @default - no propagation
   */
  readonly propagation?: Propagation;

  /**
   * Mounted read-only if true, read-write otherwise (false or unspecified).
   * Defaults to false.
   *
   * @default false
   */
  readonly readOnly?: boolean;
}

/**
 * Properties for mounting a volume.
 */
export interface VolumeMount extends ContainerMountOptions {
  /**
   * The volume to mount.
   */
  readonly volume: Volume;

  /**
   * Path within the container at which the volume should be mounted.
   * Must not contain ':'.
   */
  readonly path: string;
}

/**
 * Volume propagation options.
 */
export enum Propagation {
  /**
   * Mounts with this propagation type will receive mounts originating from
   * the host and be reflected back.
   */
  BIDIRECTIONAL = 'Bidirectional',

  /**
   * Mounts with this propagation type will receive mounts originating from
   * the host but will not reflect back.
   */
  HOST_TO_CONTAINER = 'HostToContainer',

  /**
   * Mounts with this propagation type will not receive any mounts from the
   * host and will also not reflect back.
   */
  NONE = 'None'
}

/**
 * A single application container that you want to run within a pod.
 */
export class Container {
  private readonly _volumeMounts: VolumeMount[] = [];

  public constructor() {}

  /**
   * Mounts a volume to a specific path within the container.
   * 
   * This method ensures that mounted volumes are accessible to the parent workload
   * (StatefulSet, Deployment, etc.) so they can be properly included in the pod template spec.
   */
  public mount(path: string, volume: Volume, options: ContainerMountOptions = {}) {
    this._volumeMounts.push({ path, volume, ...options });
  }

  /**
   * Returns all volume mounts configured for this container.
   * 
   * This allows parent workloads to collect all volumes from their containers
   * and include them in the pod template spec.
   */
  public get volumeMounts(): VolumeMount[] {
    return [...this._volumeMounts];
  }
}
