name: website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'chore(release)')
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.68.3'
          extended: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Build Website
        run: |
          cd website
          ./build.sh

      - name: Build Docs Site
        run: |
          ./docs/build.sh website/public/docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/public
